export const TEACHER = "Teacher"
export const STUDENT = "Student"
export const EASY = "Easy"
export const MEDIUM = "Medium"
export const HARD = "Hard"
// export const GOOGLE_CLIENT_ID="757983321900-06t2debs4i7l1anum03sjpiim8binuqq.apps.googleusercontent.com"